// libs/ui-bits/src/LoadingOverlay/LoadingOverlay.tsx
import classnames from 'classnames';
import hidden from '../hidden.module.sass';
import { Loading } from './Loading';
import styles from './LoadingOverlay.module.sass';

export const LoadingOverlay = ({ shown }: { shown?: boolean }) => (
	<div
		className={classnames(styles.LoadingOverlay, {
			[hidden.hidden]: !shown,
		})}
	>
		<Loading />
	</div>
);

// libs/si-bits/src/LoadingOverlay/LoadingOverlay.svelte
<script lang="ts">
  import Loading from './Loading.svelte';
  import h from '../hidden.module.sass';
  import styles from './LoadingOverlay.module.sass';
	import classNames from 'classnames';
  
  const { visible = false } = $props<{ visible?: boolean }>();
</script>

<div class={classNames(styles.LoadingOverlay, {
  [h.hidden]: !visible
})}>
  <Loading />
</div>
