// libs/ui-bits/src/Center.tsx
import { DetailedHTMLProps, HTMLAttributes } from 'react';

export const Center = (
	props: DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>,
) => (
	<div
		{...props}
		style={{
			display: 'flex',
			justifyContent: 'center',
			alignItems: 'center',
			width: '100%',
			height: '100%',
			textAlign: 'center',
		}}
	></div>
);

// libs/si-bits/src/Center/Center.svelte
<script lang="ts">
    const {children} = $props<{children?: ComponentType}>();
</script>
<div class="center">
    {@render children?.()}
</div>

<style>
    .center {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100%;
        height: 100%;
        text-align: center;
    }
</style>
