// libs/si-bits/src/MatchInfo/MatchInfo.svelte
<script lang="ts">
  import styles from './MatchInfo.module.sass';
  import { api } from 'monolith-ts-api';
  import type { TtfMatch, User } from '@lyku/json-models';
  import { localizeUsername } from '../localizeUsername';

  export let match: TtfMatch | undefined = undefined;
  export let user: User | undefined = undefined;

  let xUser: User | undefined;
  let oUser: User | undefined;
  let tried = false;

  $: xTurn = match?.turn && match.turn % 2;
  $: oTurn = match?.turn && match.turn % 2 === 0;

  $: if (match && !tried) {
    tried = true;
    api.getUsers([match.X, match.O])
      .then(([x, o]) => {
        xUser = x;
        oUser = o;
      })
      .catch(console.error);
  }
</script>

<div class={styles.MatchInfo}>
  <div class={`${styles.x} ${xTurn ? styles.myTurn : ''}`}>
    {localizeUsername(xUser?.username)}
  </div>
  <div class={styles.vs}>vs</div>
  <div class={`${styles.o} ${oTurn ? styles.myTurn : ''}`}>
    {localizeUsername(oUser?.username)}
  </div>
</div>

// libs/ui-bits/src/MatchInfo/MatchInfo.tsx
import styles from './MatchInfo.module.sass';
import { useEffect, useState } from 'react';
import { api } from 'monolith-ts-api';
import classnames from 'classnames';
import { TtfMatch, User } from '@lyku/json-models';
import { localizeUsername } from '../localizeUsername';

export const MatchInfo = ({
	match,
	user,
}: {
	match?: TtfMatch;
	user?: User;
}) => {
	const [tried, setTried] = useState(false);
	const [xUser, setXUser] = useState<User>();
	const [oUser, setOUser] = useState<User>();
	const xTurn = match?.turn && match.turn % 2;
	const oTurn = match?.turn && match.turn % 2 === 0;
	useEffect(() => {
		if (match && !tried) {
			setTried(true);
			api
				.getUsersById([match.X, match.O])
				.then(([x, o]) => {
					setXUser(x);
					setOUser(o);
				})
				.catch(console.error);
		}
	}, [match, tried]);
	return (
		<div className={styles.MatchInfo}>
			<div className={classnames(styles.x, { [styles.myTurn]: xTurn })}>
				{localizeUsername(xUser?.username)}
			</div>
			<div className={styles.vs}>vs</div>
			<div className={classnames(styles.o, { [styles.myTurn]: oTurn })}>
				{localizeUsername(oUser?.username)}
			</div>
		</div>
	);
};
