// libs/ui-bits/src/Agreeable/Agreeable.tsx
import { ReactNode, useState } from 'react';

import styles from './Agreeable.module.sass';

type Props = {
	onChange?: (agreed: boolean) => void | boolean;
	children?: ReactNode;
};
export const Agreeable = ({ onChange, children }: Props) => {
	const [id] = useState(Math.random().toString().substring(2));
	return (
		<div className={styles.Agreeable}>
			<input
				type="checkbox"
				id={id}
				onInput={({ currentTarget }) => onChange?.(currentTarget.checked)}
			/>
			<label htmlFor={id}>{children}</label>
		</div>
	);
};

// libs/si-bits/src/Agreeable/Agreeable.svelte
<script lang="ts">
  import styles from './Agreeable.module.sass';
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();


  let { slots } = $props<{
    slots: {
      default?: () => any;
    }
  }>();
  
  let id = Math.random().toString().substring(2);
</script>

<div class={styles.Agreeable}>
  <input
    type="checkbox"
    {id}
    oninput={e => dispatch('input', e.currentTarget.checked)}
  />
  <label {id}>
    {@render slots?.default?.()}
  </label>
</div>
