// libs/si-bits/src/Static/Static.svelte
<script lang="ts">
  import classnames from 'classnames';
  import styles from './Static.module.sass';

  export let width: number | undefined = undefined;
  export let height: number | undefined = undefined;
  export let hidden: boolean | undefined = undefined;
</script>

<div
  style="width: {width}px; height: {height}px"
  class={classnames(styles.Static, {
    [styles.hidden]: hidden,
  })}
/>

// libs/ui-bits/src/Static/Static.tsx
import classnames from 'classnames';

import styles from './Static.module.sass';

type Props = { hidden?: boolean; width?: number; height?: number };

/**
 * @noInheritDoc
 */
export const Static = ({ width, height, hidden }: Props) => (
  <div
    style={{ width, height }}
    className={classnames(styles.Static, {
      [styles.hidden]: hidden,
    })}
  ></div>
);
