// libs/si-bits/src/SubmitButton/SubmitButton.svelte
<script lang="ts">
  import styles from './SubmitButton.module.sass';

  const props = $props<{ className?: string; disabled: boolean } & any>();
  const { className, disabled, ...rest } = props;
</script>

<button 
  class={styles.SubmitButton}
  class:className
  {disabled}
  on:click
  {...rest}
>
  {children}
</button>

// libs/ui-bits/src/SubmitButton/SubmitButton.tsx
import { MouseEventHandler, ReactNode } from 'react';

import styles from './SubmitButton.module.sass';

/**
 * @noInheritDoc
 */
export const SubmitButton = (props: {
	children?: ReactNode;
	disabled?: boolean;
	onClick?: MouseEventHandler<HTMLButtonElement>;
}) => (
	<button
		className={styles.SubmitButton}
		disabled={props.disabled}
		onClick={props.onClick}
	>
		{props.children}
	</button>
);
