// libs/ui-bits/src/pages/ViewGroups.tsx
import { Button } from '../Button';
import { GroupList } from '../GroupList';
import { useState } from 'react';
import { GroupFilter } from '@lyku/json-models';

export const ViewGroups = () => {
  const [substring] = useState<string>('');
  const [filter] = useState<GroupFilter>();
  return (
    <div style={{ margin: 'auto', width: '800px', maxWidth: '100%' }}>
      <h2 style={{ display: 'flex' }}>
        Groups <Button onClick={() => alert('Coming soon!')}>+</Button>
      </h2>
      <br />
      {/*<Texticle*/}
      {/*	onInput={setSubstring}*/}
      {/*	value={substring}*/}
      {/*	pattern={group.properties.name.pattern}*/}
      {/*/>*/}
      {/*<GroupFilterSelect*/}
      {/*	value={options.find(o => o.value === filter)}*/}
      {/*	onChange={o => setFilter(o?.value)}*/}
      {/*></GroupFilterSelect>*/}
      <GroupList filter={filter} substring={substring} />
    </div>
  );
};

// libs/si-bits/src/pages/ViewGroups.svelte
<script lang="ts">
	import { Button } from '../Button.svelte';
	import { GroupList } from '../GroupList.svelte';
	import type { GroupFilter } from '@lyku/json-models';

	let substring = '';
	let filter: GroupFilter | undefined;

	function handleAddClick() {
		alert('Coming soon!');
	}
</script>

<div style="margin: auto; width: 800px; max-width: 100%">
	<h2 style="display: flex">
		Groups <Button on:click={handleAddClick}>+</Button>
	</h2>
	<br />
	<!--
	<Texticle
		on:input={e => substring = e.detail}
		value={substring}
		pattern={group.properties.name.pattern}
	/>
	<GroupFilterSelect
		value={options.find(o => o.value === filter)}
		on:change={e => filter = e.detail?.value}
	/>
	-->
	<GroupList {filter} {substring} />
</div>
