// libs/si-bits/src/pages/ViewPost.svelte
<script lang="ts">
  import { api } from 'monolith-ts-api';
  import { DynamicPost } from '../DynamicPost.svelte';
  import styles from './ViewPost.module.sass';

  const postId = BigInt(window.location.pathname.split('p/')[1]);
  const postPromise = api.getPost(postId);
</script>

<div class={styles.PostPage}>
  <main>
    {#await postPromise}
      <p>Loading...</p>
    {:then post}
      <DynamicPost {post} showReplies={true} />
    {:catch error}
      <h3>{error?.toString()}</h3>
    {/await}
  </main>
</div>

// libs/si-bits/src/pages/ViewPost.tsx
import { api } from 'monolith-ts-api';
import { DynamicPost } from '../DynamicPost';

import styles from './ViewPost.module.sass';
import { Await } from 'awaitx';

export const ViewPost = () => (
	<div className={styles.PostPage}>
		<main>
			<Await
				source={() =>
					api.getPost(BigInt(window.location.pathname.split('p/')[1]))
				}
				then={(post) => <DynamicPost post={post} showReplies={true} />}
				fail={(error) => <h3>{error?.toString()}</h3>}
			/>
		</main>
	</div>
);
