// libs/si-bits/src/Close/Close.svelte
<script lang="ts">
  import { Button } from '../Button';
  import { Crosshatch } from '../Crosshatch';
  import styles from './Close.module.sass';

  const { disabled = false, className = '' } = $props();
</script>

<Button
  {disabled}
  class={`${styles.Close} ${className}`}
  on:click
>
  <Crosshatch width="20px" bright={true} />
</Button>

// libs/ui-bits/src/Close/Close.tsx
import classnames from 'classnames';
import { FormEventHandler } from 'react';

import { Button } from '../Button';
import { Crosshatch } from '../Crosshatch';
import styles from './Close.module.sass';

type Props = {
	disabled?: boolean;
	className?: string;
	onClick?: FormEventHandler<HTMLButtonElement>;
};

/**
 * @noInheritDoc
 */
export const Close = (props: Props) => (
	<Button
		disabled={props.disabled}
		className={classnames(styles.Close, props.className)}
		onClick={props.onClick}
	>
		<Crosshatch width="20px" bright={true} />
	</Button>
);
