// libs/ui-bits/src/MobileNavLink/MobileNavLink.tsx
import { Link, LinkProps } from '../Link';
import classNames from 'classnames';
import styles from './MobileNavLink.module.sass';

export const MobileNavLink = (props: LinkProps) => (
	<Link
		{...props}
		className={classNames({
			[styles.depressed]:
				props.href && window.location.pathname.startsWith(props.href),
		})}
	/>
);

// libs/si-bits/src/MobileNavLink/MobileNavLink.svelte
<script lang="ts">
	import { Link } from '../Link';
	import styles from './MobileNavLink.module.sass';
	const { href, isActive, children, onClick } = $props<{
		href: string | undefined;
		isActive: boolean;
		children: [];
		onClick?: () => void;
	}>();
</script>

<Link {href} class={isActive ? styles.depressed : ''} {onClick}>
	{@render children?.()}
</Link>
