// libs/ui-bits/src/EmailInput.tsx
import { jsonPrimitives } from 'from-schema';

import { Texticle, TexticleProps } from './Texticle';
import { phrasebook } from './phrasebook';
const { email } = jsonPrimitives;

export const EmailInput = (props: TexticleProps) => (
  <Texticle
    type="email"
    schema={email}
    empty={phrasebook.emailFieldEmpty}
    invalid={phrasebook.emailFieldInvalid}
    valid={phrasebook.emailFieldValid}
    {...props}
  />
);

// libs/si-bits/src/EmailInput/EmailInput.svelte
<script lang="ts">
	import { jsonPrimitives } from 'from-schema';
	import { Texticle } from '../Texticle';
	import { phrasebook } from '../phrasebook';

	const { email } = jsonPrimitives;

	const props = $props();
</script>

<Texticle
	schema={email}
	empty={phrasebook.emailFieldEmpty}
	invalid={phrasebook.emailFieldInvalid}
	valid={phrasebook.emailFieldValid}
	{...props}
/>
