// libs/ui-bits/src/TvFrame/TvFrame.tsx
import classnames from 'classnames';
import { ReactNode } from 'react';

import styles from './TvFrame.module.sass';

type Props = {
  children?: ReactNode;
  size?: 'auto';
  height?: number;
  // ref?: RefObject<HTMLDivElement>;
};

/**
 * @noInheritDoc
 */
export const TvFrame = ({ children, size, height }: Props) => (
  <div
    className={classnames(styles.TvFrame, {
      [styles.auto]: size === 'auto',
    })}
    style={{ height }}
  >
    {children}
  </div>
);

// libs/si-bits/src/TvFrame/TvFrame.svelte
<script lang="ts">
	import classnames from 'classnames';
	import styles from './TvFrame.module.sass';

	const { size, height } = $props<{ size?: 'auto'; height?: number }>();
</script>

<div
	class={classnames(styles.TvFrame, {
		[styles.auto]: size === 'auto',
	})}
	style={`height: ${height}px`}
>
	{@render children?.()}
</div>
