// libs/si-bits/src/UploadButton/UploadButton.svelte
<script lang="ts">
  import { imageAndVideoMimes } from '@lyku/defaults';
  import { phrasebook } from '../phrasebook';
  import upload from '../assets/plus.svg';
  import styles from './UploadButton.module.sass';

  const id = Math.random().toString();
  const props = $props();
</script>

<input
  type="file"
  class={styles.file}
  {id}
  name="avatar"
  accept={imageAndVideoMimes}
  multiple={true}
  {...props}
/>
<label for={id}>
  <img
    src={upload}
    class={styles.UploadButton}
    alt={phrasebook.upload}
  />
</label>

// libs/ui-bits/src/UploadButton/UploadButton.tsx
import { imageAndVideoMimes } from '@lyku/defaults';
import { useState } from 'react';

import { phrasebook } from '../phrasebook';
import upload from '../assets/plus.svg';
import styles from './UploadButton.module.sass';

export const UploadButton = ({
  onChange,
}: {
  onChange: React.ChangeEventHandler<HTMLInputElement>;
}) => {
  const [id] = useState(Math.random().toString());
  return (
    <>
      <input
        type="file"
        className={styles.file}
        id={id}
        name="avatar"
        accept={imageAndVideoMimes}
        multiple={true}
        onChange={onChange}
      />
      <label htmlFor={id}>
        <img
          src={upload}
          className={styles.UploadButton}
          alt={phrasebook.upload}
        />
      </label>
    </>
  );
};
