// libs/ui-bits/src/ChatBox/MessageItem.tsx
import { useCacheSingleton } from '../CacheProvider/CacheProvider';
import styles from './MessageItem.module.sass';
import { Message, User } from '@lyku/json-models';

export const MessageItem = ({ src }: { src: Message }) => (
	<li className={styles.MessageItem}>
		<b>{useCacheSingleton('users', src.author)[0]?.username ?? '-'}:&nbsp;</b>
		{src.content}
	</li>
);

// libs/si-bits/src/ChatBox/MessageItem.svelte
<script lang="ts">
  import styles from './MessageItem.module.sass';
  import type { Message } from '@lyku/json-models';
  import { getContext } from 'svelte';

  export let src: Message;
  
  // Replace useCacheSingleton with getContext
  const cache = getContext('cache');
  $: user = $cache.users?.[src.author] ?? null;
</script>

<li class={styles.MessageItem}>
  <b>{user?.username ?? '-'}:&nbsp;</b>
  {src.content}
</li>
