// libs/ui-bits/src/Divisio.tsx
import { Property } from 'csstype';

import React, { CSSProperties, ReactNode } from 'react';
import { Size, sizes } from './sizes';

const layouts = { h: 'row', v: 'column' } as const;
type Layout = keyof typeof layouts;

type SeparateProps = {
  size: Size;
  layout: Layout;
  children: ReactNode;
  fill?: boolean;
  hang?: ReactNode;
  alignItems?: Property.AlignItems;
  style?: CSSProperties;
};
export const Divisio = ({
  size,
  layout,
  children,
  fill,
  hang,
  alignItems,
  style,
}: SeparateProps) => (
  <div
    style={{
      ...style,
      position: 'relative',
      display: 'flex',
      flexDirection: layouts[layout],
      gap: sizes[size],
      ...(fill ? { width: '100%' } : {}),
      alignItems,
    }}
  >
    {children}
    {hang && (
      <div style={{ position: 'absolute', top: 0, right: 0 }}>{hang}</div>
    )}
  </div>
);

// libs/si-bits/src/Divisio/Divisio.svelte
<script lang="ts">
    import type { Property } from 'csstype';
    import type { ComponentType, CSSProperties } from 'react';
    import { type Size, sizes } from '../sizes';

    const layouts = { h: 'row', v: 'column' } as const;
    type Layout = keyof typeof layouts;

    const { size, layout, fill, hang, alignItems, style = {}, children } = $props<{ size: Size; layout: Layout; fill: boolean; hang: any; alignItems: Property.AlignItems | undefined; style: CSSProperties, children?: ComponentType }>();
</script>

<div
    style="
        position: relative;
        display: flex;
        flex-direction: {layouts[layout]};
        gap: {sizes[size]};
        {fill ? 'width: 100%;' : ''}
        align-items: {alignItems || ''};
        {Object.entries(style).map(([key, value]) => `${key}: ${value};`).join(' ')}
    "
>
    {@render children?.()}
    {#if hang}
        <div style="position: absolute; top: 0; right: 0">
            {hang}
        </div>
    {/if}
</div>
