// libs/si-bits/src/Cards/Cards.svelte
<script lang="ts">
  import { Card } from '../Card';
  import { Cardless } from '../Cardless';
  import styles from './Cards.module.sass';

  type Props = {
    children?: any[];
  };

  const { children = [] } = $props();
</script>

<div class={styles.Cards}>
  {#each children || [] as child, i (i)}
    {#if child.type === Cardless.name}
      <span>{child}</span>
    {:else}
      <Card>{child}</Card>
    {/if}
  {/each}
</div>

// libs/ui-bits/src/Cards/Cards.tsx
import { ReactElement } from 'react';

import { Card } from '../Card/Card';
import { Cardless } from '../Cardless';
import styles from './Cards.module.sass';

type Props = { children?: ReactElement[] };

/**
 * @noInheritDoc
 */
export const Cards = ({ children }: Props) => (
  <div className={styles.Cards}>
    {children?.map((child, i) => {
      return child.type === Cardless.name ? (
        <span key={i}>child</span>
      ) : (
        <Card key={i}>{child}</Card>
      );
    })}
  </div>
);
