// libs/ui-bits/src/WinPanel.tsx
import { TtfMatch, User } from '@lyku/json-models';
import { Link } from './Link';

export const WinPanel = ({ user, match }: { user?: User; match: TtfMatch }) => (
	<>
		{user?.id === match.winner ? (
			<>
				<h1>You won!</h1>
				{!user?.id && (
					<h3>Make an account to earn points when you win!</h3>
				)}
			</>
		) : (
			<h1>You lost.</h1>
		)}
		<Link href={'#'}>Play again</Link>
	</>
);

// libs/si-bits/src/WinPanel/WinPanel.svelte
<script lang="ts">
  import type { TtfMatch, User } from '@lyku/json-models';
  import { Link } from '../Link';

  export let user: User | undefined = undefined;
  export let match: TtfMatch;
</script>

{#if user?.id === match.winner}
  <h1>You won!</h1>
  {#if !user?.id}
    <h3>Make an account to earn points when you win!</h3>
  {/if}
{:else}
  <h1>You lost.</h1>
{/if}

<Link href={'#'}>Play again</Link>
