// libs/si-bits/src/ChatBox/ChatBox.svelte
<script lang="ts">
    import { api } from 'monolith-ts-api';
    import styles from './ChatBox.module.sass';
    import { MessageItem } from './MessageItem.svelte';
    import type { Channel, Message } from '@lyku/json-models';

    export let channel: Channel | undefined = undefined;
    let messages: Message[] = [];

    $: if (channel) {
        api.listMessages({ channel: channel.id })
            .then(({ messages: newMessages }) => {
                messages = newMessages;
                console.log('messages', messages);
            });
    }
</script>

<div class={styles.ChatBox}>
    <ul class={styles.MessageList}>
        {#each messages as msg (msg.id)}
            <MessageItem src={msg} />
        {/each}
    </ul>
</div>

// libs/ui-bits/src/ChatBox/ChatBox.tsx
import { api } from 'monolith-ts-api';
import { useEffect, useState } from 'react';

import styles from './ChatBox.module.sass';
import { MessageItem } from './MessageItem';
import { Channel, Message } from '@lyku/json-models';

export type Props = { channel?: Channel };
export type State = { messages: Message[] };

/**
 * @noInheritDoc
 */
export const ChatBox = (props: Props) => {
  const [messages, setMessages] = useState<Message[]>([]);
  useEffect(() => {
    if (!props.channel) return;
    void api
      .listMessages({ channel: props.channel.id })
      .then(({ messages }) => setMessages(messages));
    console.log('messages', messages);
  }, [props, messages]);
  return (
    <div className={styles.ChatBox}>
      <ul className={styles.MessageList}>
        {messages.map((msg) => (
          <MessageItem src={msg} key={msg.id}></MessageItem>
        ))}
      </ul>
    </div>
  );
};
