// libs/si-bits/src/FollowUser/FollowUser.svelte
<script lang="ts">
  import { CoolLink } from '../CoolLink';
  import { api } from 'monolith-ts-api';
  import { phrasebook } from '../phrasebook';
  import type { User } from '@lyku/json-models';

  export let user: User;

  let following: boolean | undefined;
  let queried = false;

  $: if (!queried && following === undefined) {
    queried = true;
    api.amIFollowing(user.id).then((r) => {
      following = r;
      queried = false;
    });
  }
</script>

{#if typeof following === 'boolean'}
  {#if following}
    <CoolLink
      on:click={() => {
        following = undefined;
        api.unfollowUser(user.id).then(() => following = false);
      }}
    >
      {phrasebook.unfollow} &ndash;
    </CoolLink>
  {:else}
    <CoolLink
      on:click={() => {
        following = undefined;
        api.followUser(user.id).then(() => following = true);
      }}
    >
      {phrasebook.follow} +
    </CoolLink>
  {/if}
{/if}

// libs/ui-bits/src/FollowUser/FollowUser.tsx
import { CoolLink } from '../CoolLink';
import { api } from 'monolith-ts-api';
import { useState } from 'react';
import { User } from '@lyku/json-models';
import { phrasebook } from '../phrasebook';

export const FollowUser = ({ user }: { user: User }) => {
	// const [status, setStatus] = useState<FromSchema<typeof friendshipStatus>>();
	const [following, setFollowing] = useState<boolean>();
	const [queried, setQueried] = useState(false);
	useState(() => {
		if (queried || following) return;
		setQueried(true);
		api.amIFollowing(user.id).then((r) => {
			setFollowing(r);
			setQueried(false);
		});
	});
	return (
		typeof following === 'boolean' &&
		(following ? (
			<CoolLink
				onClick={() => {
					setFollowing(undefined);
					api.unfollowUser(user.id).then(() => setFollowing(false));
				}}
			>
				{phrasebook.unfollow} &ndash;
			</CoolLink>
		) : (
			<CoolLink
				onClick={() => {
					setFollowing(undefined);
					api.followUser(user.id).then(() => setFollowing(true));
				}}
			>
				{phrasebook.follow} +
			</CoolLink>
		))
	);
};
