// libs/si-bits/src/PopupOverlay/PopupBox.svelte
<script lang="ts">
  import styles from './PopupBox.module.sass';

  const { overlay, buttonContent } = $props<{ overlay: string; buttonContent: any }>();

  function dismiss() {
    window.dispatchEvent(new Event(`hide${overlay}`));
  }
</script>

<div class={styles.WinBox}>
  <button aria-label="Close" class={styles.close} onclick={dismiss}></button>
  {children}
  {#if buttonContent}
    <button aria-label="Dismiss" class={styles.action} onclick={dismiss}>
      {buttonContent}
    </button>
  {/if}
</div>

// libs/ui-bits/src/PopupOverlay/PopupBox.tsx
import { ReactNode, useCallback } from 'react';

import styles from './PopupBox.module.sass';

export const PopupBox = (props: {
	children?: ReactNode;
	overlay: string;
	buttonContent?: ReactNode;
}) => {
	const dismiss = useCallback(
		() => window.dispatchEvent(new Event(`hide${props.overlay}`)),
		[props.overlay],
	);
	return (
		<div className={styles.WinBox}>
			<button className={styles.close} onClick={dismiss}></button>
			{props.children}
			{props.buttonContent && (
				<button className={styles.action} onClick={dismiss}>
					this.props.buttonContent
				</button>
			)}
		</div>
	);
};
