// libs/si-bits/src/UsernameInput/UsernameInput.svelte
<script lang="ts">
  import { username } from '@lyku/json-models';
  import {Texticle} from '../Texticle';
  import { phrasebook } from '../phrasebook';

  const props = $props();
</script>

<Texticle
  schema={username}
  empty={phrasebook.usernameFieldEmpty}
  invalid={phrasebook.usernameFieldInvalid}
  valid={phrasebook.usernameFieldValid}
  {...props}
/>

// libs/ui-bits/src/UsernameInput.tsx
import { username } from '@lyku/json-models';

import { Texticle, TexticleProps } from './Texticle';
import { phrasebook } from './phrasebook';

export const UsernameInput = (props: TexticleProps) => (
	<Texticle
		schema={username}
		empty={phrasebook.usernameFieldEmpty}
		invalid={phrasebook.usernameFieldInvalid}
		valid={phrasebook.usernameFieldValid}
		{...props}
	/>
);
