// libs/si-bits/src/Crosshatch/Crosshatch.svelte
<script lang="ts">
  import classnames from 'classnames';
  import styles from './Crosshatch.module.sass';

  export let width: string | undefined = undefined;
  export let height: string | undefined = undefined;
  export let style: Record<string, string> = {};
  export let bright: boolean = false;
</script>

<div
  class={classnames(styles.Crosshatch, { [styles.bright]: bright })}
  style:width={width}
  style:height={height}
  {...style}
></div>

// libs/ui-bits/src/Crosshatch/Crosshatch.tsx
import classnames from 'classnames';
import { CSSProperties } from 'react';

import styles from './Crosshatch.module.sass';

export const Crosshatch = ({
  width,
  height,
  style,
  bright,
}: {
  width?: string;
  height?: string;
  style?: CSSProperties;
  bright?: boolean;
}) => (
  <div
    className={classnames(styles.Crosshatch, { [styles.bright]: bright })}
    style={{ ...style, width, height }}
  />
);
