// libs/si-bits/src/Texticle/Texticle.svelte
<script lang="ts">
  import type { StringJsonSchema } from 'from-schema';
  import styles from './Texticle.module.sass';
  
  type Type = 'text' | 'email' | 'password';
  
  export let schema: StringJsonSchema | undefined = undefined;
  export let empty: string = '';
  export let valid: string | undefined = undefined;
  export let invalid: string | undefined = undefined;
  export let onInput: ((text: string) => void) | undefined = undefined;
  export let onValidation: ((valid: boolean) => void | boolean) | undefined = undefined;
  export let pattern: string | undefined = undefined;
  export let type: Type = 'text';
  export let minLength: number | undefined = undefined;
  export let maxLength: number | undefined = undefined;
  export let multiline: boolean = false;
  export let value: string = '';

  let label = empty;
  let isValid = false;
  let isInvalid = false;
  const id = Math.random().toString().substring(2);

  function validate(text: string): boolean {
    const patternToUse = pattern ?? schema?.pattern;
    if (patternToUse && !RegExp(patternToUse).test(text)) return false;
    const minlen = minLength ?? schema?.minLength;
    if (minlen && text.length < minlen) return false;
    const maxlen = maxLength ?? schema?.maxLength;
    if (maxlen && text.length > maxlen) return false;
    return true;
  }

  function handleInput(event: Event) {
    const target = event.target as HTMLInputElement | HTMLTextAreaElement;
    value = target.value;
    onInput?.(value);
    updatePlaceholder();
  }

  function updatePlaceholder() {
    isValid = validate(value);
    isInvalid = !isValid;
    label = value
      ? isValid
        ? valid ?? empty
        : invalid ?? empty
      : empty;
    label = label ?? empty ?? ' ';
    onValidation?.(isValid);
  }

  $: value, empty, updatePlaceholder();
</script>

<div class={styles.Texticle} class:valid={isValid} class:invalid={isInvalid}>
  {#if multiline}
    <textarea
      {id}
      on:input={handleInput}
      placeholder="-"
      bind:value
    ></textarea>
  {:else}
    <input
      {id}
      on:input={handleInput}
      placeholder="-"
      {type}
      bind:value
    />
  {/if}
  <label for={id}>{label}</label>
</div>

// libs/ui-bits/src/Texticle/Texticle.tsx
import classnames from 'classnames';
import { FormEventHandler, useEffect, useState } from 'react';

import styles from './Texticle.module.sass';
import { StringJsonSchema } from 'from-schema';

export type OnInput = (text: string) => void;
export type OnValidation = (valid: boolean) => void | boolean;
type Type = 'text' | 'email' | 'password';
export type TexticleProps = {
  schema?: StringJsonSchema;
  empty?: string;
  valid?: string;
  invalid?: string;
  onInput?: OnInput;
  onValidation?: OnValidation;
  pattern?: string;
  type?: Type;
  minLength?: number;
  maxLength?: number;
  multiline?: boolean;
  value?: string;
};

/**
 * @noInheritDoc
 */
export const Texticle = (props: TexticleProps) => {
  const [label, setLabel] = useState(props.empty ?? '');
  const [valid, setValid] = useState(false);
  const [invalid, setInvalid] = useState(false);
  const [value, setValue] = useState('');
  const id = Math.random().toString().substring(2);
  const validate: (text: string) => boolean = (text: string) => {
    const pattern = props.pattern ?? props.schema?.pattern;
    if (pattern && !RegExp(pattern).test(text)) return false;
    const minlen = props.minLength ?? props.schema?.minLength;
    if (minlen && text.length < minlen) return false;
    const maxlen = props.maxLength ?? props.schema?.maxLength;
    if (maxlen && text.length > maxlen) return false;
    return true;
  };
  const onInput: FormEventHandler<HTMLInputElement | HTMLTextAreaElement> = (
    ev,
  ) => {
    const { value } = ev.currentTarget;
    setValue(value);
    props.onInput?.(value);
    doPlaceholder();
  };
  const doPlaceholder = () => {
    const isValid = validate(value);
    setValid(isValid);
    setInvalid(!isValid);
    const label = value
      ? isValid
        ? (props.valid ?? props.empty)
        : (props.invalid ?? props.empty)
      : props.empty;
    setLabel(label ?? props.empty ?? ' ');
  };
  useEffect(doPlaceholder, [props.empty, value, doPlaceholder]);
  useEffect(() => void props.onValidation?.(valid), [props, valid]);
  return (
    <div
      className={classnames(styles.Texticle, {
        valid: valid,
        invalid: invalid,
      })}
    >
      {props.multiline ? (
        <textarea id={id} onChange={onInput} placeholder={'-'}>
          {props.value}
        </textarea>
      ) : (
        <input
          id={id}
          onChange={onInput}
          placeholder={'-'}
          type={props.type ?? 'text'}
          defaultValue={props.value}
        />
      )}
      <label htmlFor={id}>{label}</label>
    </div>
  );
};
