// libs/si-bits/src/PostList/PostList.svelte
<script lang="ts">
  import type { Post } from '@lyku/json-models';
  import { DynamicPost } from '../DynamicPost';
  import styles from './PostList.module.sass';

  export let posts: Post[];
  export let inset: number | undefined = undefined;
  export let placeholder: any = undefined;
</script>

<div class={`${styles.PostList} ${inset ? styles.inset : ''}`}>
  {#if posts?.length}
    {#each posts as post (post.id)}
      <DynamicPost {post} autoplay={false} />
    {/each}
  {:else}
    {placeholder}
  {/if}
</div>

// libs/ui-bits/src/PostList/PostList.tsx
import classnames from 'classnames';
import { ReactNode } from 'react';

import { DynamicPost } from '../DynamicPost';

import styles from './PostList.module.sass';
import { Post } from '@lyku/json-models';

type Props = {
	posts: Post[];
	inset?: number;
	placeholder?: ReactNode;
};

export const PostList = ({ posts, inset, placeholder }: Props) => (
	<div className={classnames(styles.PostList, { [styles.inset]: inset })}>
		{posts?.length
			? posts.map(post => (
					<DynamicPost post={post} key={post.id} autoplay={false} />
				))
			: placeholder}
	</div>
);
