// libs/si-bits/src/Link/Link.svelte
<script lang="ts">
	import classnames from 'classnames';
	import styles from './Link.module.sass';
	import type { ClassValue } from 'svelte/elements';
	const {
		disabled = false,
		class: className = '',
		href,
		target,
		children,
		onClick,
		...rest
	} = $props<{
		disabled?: boolean;
		class?: ClassValue;
		href?: string;
		target?: string;
		children: [];
		[key: string]: any;
		onClick?: () => void;
	}>();

	const classes = $derived(classnames(styles.Link, className));

	// Add security check for external links
	const rel = $derived(target === '_blank' ? 'noopener noreferrer' : undefined);
</script>

{#if href}
	<a
		{href}
		{target}
		{rel}
		class={classes}
		onclick={onClick}
		aria-disabled={disabled}
		{...rest}
	>
		{@render children?.()}
	</a>
{:else}
	<button type="button" class={classes} {disabled} onclick={onClick} {...rest}>
		{@render children?.()}
	</button>
{/if}

// libs/ui-bits/src/Link/Link.tsx
import classnames from 'classnames';
import { MouseEventHandler, ReactNode } from 'react';

import styles from './Link.module.sass';

export type LinkProps = {
  disabled?: boolean;
  className?: string;
  children?: ReactNode;
  onClick?: MouseEventHandler<HTMLButtonElement | HTMLAnchorElement>;
  href?: string;
  target?: string;
};

/**
 * @noInheritDoc
 */
export const Link = (props: LinkProps) => {
  const pps = {
    ...props,
    className: classnames(styles.Link, props.className),
  };
  return 'href' in props ? (
    <a {...pps}>{pps.children}</a>
  ) : (
    <button {...pps}>{pps.children}</button>
  );
};
