// libs/si-bits/src/VideoList/MessageItem.tsx
import { useCacheSingleton } from 'ui-bits';
import styles from './MessageItem.module.sass';
import { Message } from '@lyku/json-models';

export type Props = {
	src: Message;
};

export const MessageItem = ({ src }: Props) => (
	<li className={styles.MessageItem}>
		<b>{useCacheSingleton('users', src.author)[0]?.username}:&nbsp;</b>
		{src.content}
	</li>
);

// libs/si-bits/src/VideoList/MessageItem.svelte
<script lang="ts">
  import { useCacheSingleton } from 'ui-bits';
  import styles from './MessageItem.module.sass';
  import type { Message } from '@lyku/json-models';

  export let src: Message;

  const [author] = useCacheSingleton('users', src.author);
</script>

<li class={styles.MessageItem}>
  <b>{author?.username}:&nbsp;</b>
  {src.content}
</li>
