// libs/si-bits/src/VideoList/VideoList.svelte
<script lang="ts">
  import { api } from 'monolith-ts-api';
  import { phrasebook } from '../phrasebook';
  import styles from './VideoList.module.sass';
  import type { Channel, ListChannelVideosResponse } from '@lyku/json-models';

  const { channel } = $props<{ channel: Channel }>();

  const loadVideos = () => api.listChannelVideos({ channelId: channel.id });
  

  let videosPromise: ListChannelVideosResponse | undefined = $state(undefined);
  
  $effect(() => {
    if (channel.id) {
      videosPromise = loadVideos();
    }
  });
</script>

<div>
  <h2>Shelf</h2>
  {#await videosPromise}
    <p>Loading...</p>
  {:catch error}
    <h1>{error}</h1>
  {:then videos}
    <ul class={styles.VideoList}>
      {#each videos as video (video.uid)}
        <li>
          <img src={video.thumbnail} alt={phrasebook.videoThumbnail} />
        </li>
      {/each}
    </ul>
  {/await}
</div>

// libs/si-bits/src/VideoList/VideoList.tsx
import { api } from 'monolith-ts-api';

import { phrasebook } from '../phrasebook';
import styles from './VideoList.module.sass';
import { Channel } from '@lyku/json-models';
import { Await } from 'awaitx';

type Props = { channel: Channel };

export const VideoList = ({ channel }: Props) => (
	<div>
		<h2>Shelf</h2>
		<Await
			dependencies={[channel.id]}
			source={() => api.listChannelVideos({ channelId: channel.id })}
			fail={(error) => <h1>{String(error)}</h1>}
			then={(videos) => (
				<ul className={styles.VideoList}>
					{videos.map((video) => (
						<li key={video.uid}>
							<img src={video.thumbnail} alt={phrasebook.videoThumbnail} />
						</li>
					))}
				</ul>
			)}
		/>
	</div>
);
