// libs/ui-bits/src/GroupList/GroupList.tsx
import { api, sessionId } from 'monolith-ts-api';
import { useEffect, useState } from 'react';
import { Group, GroupFilter, GroupMembership } from '@lyku/json-models';
import { Button } from '../Button';
import { useCurrentUser } from '../currentUserStore';

export const GroupList = ({
	substring,
	filter,
}: {
	substring?: string;
	filter?: GroupFilter;
}) => {
	const user = useCurrentUser();
	const [groups, setGroups] = useState<Group[]>([]);
	const [memberships, setMemberships] = useState<GroupMembership[]>([]);
	const [queriedGroups, setQueriedGroups] = useState(false);
	useEffect(() => {
		if (queriedGroups) return;
		if (sessionId) {
			setQueriedGroups(true);
			api.listGroups({ filter, substring }).then(
				({ groups, memberships }) => {
					setGroups(groups);
					setMemberships(memberships);
				},
			);
		} else {
			setQueriedGroups(true);
			api.listGroupsUnauthenticated({ substring }).then(setGroups);
		}
	}, [queriedGroups, groups, memberships, filter, substring]);
	return groups.length ? (
		<ul>
			{groups.map(g => (
				<li>
					<h3>{g.name}</h3>
					{user &&
					memberships.find(m => m.group === g.id) &&
					g.owner !== user.id ? (
						<Button onClick={() => alert('Coming soon!')}>
							Leave
						</Button>
					) : (
						<Button onClick={() => alert('Coming soon!')}>
							Join
						</Button>
					)}
				</li>
			))}
		</ul>
	) : (
		"You're not in any groups!"
	);
};

// libs/si-bits/src/GroupList/GroupList.svelte
<script lang="ts">
  import { api, getSessionId } from 'monolith-ts-api';
  import type { Group, GroupFilter, GroupMembership } from '@lyku/json-models';
  import { Button } from '../Button';
  import { currentUser } from '../currentUserStore';
  import styles from './GroupList.module.sass';

  export let substring: string | undefined = undefined;
  export let filter: GroupFilter | undefined = undefined;

  let groups: Group[] = [];
  let memberships: GroupMembership[] = [];
  let queriedGroups = false;

  $: if (!queriedGroups && getSessionId()) {
    queriedGroups = true;
    api.listGroups({ filter, substring }).then(({ groups: g, memberships: m }) => {
      groups = g;
      memberships = m;
    });
  } else if (!queriedGroups) {
    queriedGroups = true;
    api.listGroupsUnauthenticated({ substring }).then(g => {
      groups = g;
    });
  }
</script>

{#if groups.length}
  <ul>
    {#each groups as g (g.id)}
      <li>
        <h3>{g.name}</h3>
        {#if $currentUser && memberships.find((m) => m.group === g.id) && g.owner !== $currentUser.id}
          <Button on:click={() => alert('Coming soon!')}>Leave</Button>
        {:else}
          <Button on:click={() => alert('Coming soon!')}>Join</Button>
        {/if}
      </li>
    {/each}
  </ul>
{:else}
  <p>You're not in any groups!</p>
{/if}
