// libs/ui-bits/src/PostCreator/PostCreator.tsx
import { Editor } from '@tinymce/tinymce-react';
import classnames from 'classnames';
import { safeTags } from '@lyku/helpers';
import { api } from 'monolith-ts-api';
import { useEffect, useState } from 'react';

// import { AttachmentDraft, User, Uuid } from 'types';
import {
	AttachmentMime,
	User,
	ImageDraft,
	VideoDraft,
} from '@lyku/json-models';
import { Button } from '../Button';
import { Crosshatch } from '../Crosshatch';
import { DynamicPost } from '../DynamicPost';
import dynaPost from '../DynamicPost/DynamicPost.module.sass';
import { ImageUpload, defaultImages } from '../ImageUpload';
import { Link } from '../Link';
import { ProfilePicture } from '../ProfilePicture';
import { UploadButton } from '../UploadButton';
import chevvy from '../assets/chevvy.svg';
import { phrasebook } from '../phrasebook';
import styles from './PostCreator.module.sass';
import { useCacheSingleton } from '../CacheProvider';

type Props = {
	user: User;
	reply?: bigint;
	echo?: bigint;
	showInset?: boolean;
};

export const PostCreator = ({
	user: { profilePicture, username },
	reply,
	echo,
	showInset,
}: Props) => {
	const [id, setId] = useState<bigint>();
	const [body, setBody] = useState('');
	const [error, setError] = useState<string>();
	const [postable, setPostable] = useState(false);
	// const [echoPost, setEchoPost] = useState<ViewPost>();
	// const [replyToPost, setReplyToPost] = useState<ViewPost>();
	const [files, setFiles] = useState<File[]>([]);
	// const [packs, setPacks] = useState<AttachmentDraft[]>();
	const [imageDrafts, setImageDrafts] = useState<ImageDraft[]>();
	const [videoDrafts, setVideoDrafts] = useState<VideoDraft[]>();
	const [pending, setPending] = useState(0);
	const [finalizing, setFinalizing] = useState(false);

	const [replyToPost] = useCacheSingleton('posts', reply);
	const [echoPost] = useCacheSingleton('posts', echo);
	const submitText = echoPost
		? phrasebook.echo
		: replyToPost
			? phrasebook.reply
			: phrasebook.post;
	const clear = () => {
		setId(undefined);
		setBody('');
		setError(undefined);
		setPostable(false);
		setFiles([]);
		setImageDrafts([]);
		setVideoDrafts([]);
		setPending(0);
		setFinalizing(false);
	};
	useEffect(() => {
		console.log('pending', pending, 'finalizing', finalizing, 'id', id);
		if (pending || finalizing || !id) return;
		console.log('Finalizing post', id);
		setFinalizing(true);
		api.finalizePost({ id }).then((res) => {
			window.location.pathname = `/p/${id}`;
			console.log('ViewPost finalization:', res);
			setFinalizing(false);
			clear();
		});
	}, [pending, finalizing, id]);
	useEffect(() => {
		setPostable((files || body?.length > 0) && !error);
	}, [files, body, error]);
	const post = async () => {
		console.log('submitting', body);
		setPending(files.length);
		const { error, id, imageDrafts, videoDrafts } = await api.draftPost({
			body,
			attachments: files.map(({ type, size }) => ({
				type: type as AttachmentMime,
				size,
			})),
			replyTo: replyToPost?.id,
			echoing: echoPost?.id,
		});
		if (!id) {
			setError(error ?? phrasebook.unknownFrontendError);
			return;
		}
		setId(id);
		setImageDrafts(imageDrafts);
		setVideoDrafts(videoDrafts);
		console.log(
			'ViewPost submitted successfully.',
			imageDrafts ?? 'No images',
			videoDrafts ?? 'No videos',
		);
	};
	console.log('Files', files);
	const depend = () => setPending((p) => p - 1);
	const placeholder = echoPost
		? phrasebook.postBodyEchoPlaceholder
		: replyToPost
			? phrasebook.postBodyReplyPlaceholder
			: phrasebook.postBodyStandardPlaceholder;
	return (
		<div className={styles.PostCreator}>
			{showInset && replyToPost && (
				<DynamicPost post={replyToPost} inset="reply" />
			)}
			<div className={classnames({ [styles.newPost]: replyToPost })}>
				{replyToPost && (
					<span className={dynaPost.hatchInset}>
						<Crosshatch width="20px" height="100%" />
					</span>
				)}
				<div className={styles.UserDetails}>
					<ProfilePicture
						url={profilePicture ?? defaultImages.ProfilePicture}
						size="m"
					/>
					<Link className={styles.Username}>{username}</Link>
				</div>
				<div className={styles.editBox}>
					<UploadButton
						onChange={(e) =>
							e.currentTarget.files &&
							setFiles([...files, ...Array.from(e.currentTarget.files)])
						}
					/>
					<span className={styles.editor}>
						<Editor
							init={{
								// editable_class: styles.editable,
								menubar: false,
								toolbar: false,
								inline: true,
								plugins: ['wordcount'],
								valid_elements: safeTags.join(','),
								// body_class: styles.editor,
								placeholder,
							}}
							apiKey={'n8aknziwp4321kn27h8m3pw30sj42t7akub6yexbtpm0wv5d'}
							onEditorChange={(newVal, editor) => setBody(newVal)}
							// onInit={(event, editor) => editorRef.current = editor}
						/>
					</span>
				</div>
				<div className={styles.imageList}>
					{files.map((file, f) => {
						const pack =
							imageDrafts?.find((d) => d.filename === file.name) ??
							videoDrafts?.find((d) => d.filename === file.name);
						return (
							<ImageUpload
								key={file.name}
								reason="PostAttachment"
								file={file}
								working={Boolean(pending) || Boolean(pack)}
								removeClicked={
									pending
										? undefined
										: () =>
												setFiles(files.slice(0, f).concat(files.slice(f + 1)))
								}
								attachmentUploadPack={pack}
								onUpload={depend}
								allowVideo={true}
							/>
						);
					})}
				</div>
				<div className={styles.Submit}>
					<Button onClick={post} disabled={!postable}>
						<span>{submitText}</span>
						<img src={chevvy} alt={submitText} aria-hidden={true} />
					</Button>
				</div>
				{error && <div className={styles.Error}>{error}</div>}
				{showInset && echoPost && <DynamicPost post={echoPost} inset="echo" />}
			</div>
		</div>
	);
};

// libs/si-bits/src/PostCreator/PostCreator.svelte
<script lang="ts">
  import { default as Editor } from '@tinymce/tinymce-svelte';
  import { safeTags } from '@lyku/helpers';
  import { api } from 'monolith-ts-api';
  import type {
    AttachmentMime,
    User,
    ImageDraft,
    VideoDraft,
  } from '@lyku/json-models';
  
  import { Button } from '../Button';
  import { Crosshatch } from '../Crosshatch';
  import { DynamicPost } from '../DynamicPost';
  import dynaPost from '../DynamicPost/DynamicPost.module.sass';
  import { ImageUpload, defaultImages } from '../ImageUpload';
  import { Link } from '../Link';
  import { ProfilePicture } from '../ProfilePicture';
  import { UploadButton } from '../UploadButton';
  import chevvy from '../assets/chevvy.svg';
  import { phrasebook } from '../phrasebook';
  import styles from './PostCreator.module.sass';
  import { cacheStore } from '../CacheProvider';

  const { user, reply = undefined, echo = undefined, showInset = undefined } = $props<{
    user: User;
    reply?: bigint;
    echo?: bigint; 
    showInset?: boolean;
  }>();

  let id: bigint | undefined;
  let body = '';
  let error: string | undefined;
  let files: File[] = [];
  let imageDrafts: ImageDraft[] | undefined;
  let videoDrafts: VideoDraft[] | undefined;
  let pending = 0;
  let finalizing = false;

  const replyToPost = $derived(() => {
    if (!reply) return undefined;
    return cacheStore.caches.posts.get(reply);
  });

  const echoPost = $derived(() => {
    if (!echo) return undefined;
    return cacheStore.caches.posts.get(echo);
  });

  $effect(() => {
    if (reply && !replyToPost) {
      cacheStore.posts.fetch(reply);
    }
  });

  $effect(() => {
    if (echo && !echoPost) {
      cacheStore.posts.fetch(echo);
    }
  });

  const submitText = $derived(() => {
    return echoPost
      ? phrasebook.echo
      : replyToPost
      ? phrasebook.reply
      : phrasebook.post;
  });

  function clear() {
    id = undefined;
    body = '';
    error = undefined;
    // postable = false;
    files = [];
    imageDrafts = [];
    videoDrafts = [];
    pending = 0;
    finalizing = false;
  }

  $effect(() => {
    if (!pending && !finalizing && id) {
      console.log('Finalizing post', id);
      finalizing = true;
      api.finalizePost({ id }).then((res) => {
        window.location.pathname = `/p/${id}`;
        console.log('ViewPost finalization:', res);
        finalizing = false;
        clear();
      });
    }
  });

  const postable = $derived(() => {
    return (files.length || body?.length > 0) && !error;
  });

  async function post() {
    console.log('submitting', body);
    pending = files.length;
    const result = await api.draftPost({
      body,
      attachments: files.map(({ type, size }) => ({
        type: type as AttachmentMime,
        size,
      })),
      replyTo: replyToPost?.id,
      echoing: echoPost?.id,
    });

    if (!result.id) {
      error = result.error ?? phrasebook.unknownFrontendError;
      return;
    }

    id = result.id;
    imageDrafts = result.imageDrafts;
    videoDrafts = result.videoDrafts;
    console.log(
      'ViewPost submitted successfully.',
      imageDrafts ?? 'No images',
      videoDrafts ?? 'No videos'
    );
  }

  function depend() {
    pending -= 1;
  }

  const placeholder = $derived(() => {
    return echoPost
      ? phrasebook.postBodyEchoPlaceholder
      : replyToPost
      ? phrasebook.postBodyReplyPlaceholder
      : phrasebook.postBodyStandardPlaceholder;
  });

  function handleFileChange(e: Event) {
    const target = e.currentTarget as HTMLInputElement;
    if (target.files) {
      files = [...files, ...Array.from(target.files)];
    }
  }
</script>

<div class={styles.PostCreator}>
  {#if showInset && replyToPost}
    <DynamicPost post={replyToPost} inset="reply" />
  {/if}
  
  <div class:${styles.newPost}={replyToPost}>
    {#if replyToPost}
      <span class={dynaPost.hatchInset}>
        <Crosshatch width="20px" height="100%" />
      </span>
    {/if}
    
    <div class={styles.UserDetails}>
      <ProfilePicture
        url={user.profilePicture ?? defaultImages.ProfilePicture}
        size="m"
      />
      <Link class={styles.Username}>{user.username}</Link>
    </div>

    <div class={styles.editBox}>
      <UploadButton on:change={handleFileChange} />
      <span class={styles.editor}>
        <Editor
          init={{
            menubar: false,
            toolbar: false,
            inline: true,
            plugins: ['wordcount'],
            valid_elements: safeTags.join(','),
            placeholder,
          }}
          apiKey={'n8aknziwp4321kn27h8m3pw30sj42t7akub6yexbtpm0wv5d'}
          onEditorChange={(newVal) => body = newVal}
        />
      </span>
    </div>

    <div class={styles.imageList}>
      {#each files as file, f}
        {@const pack = imageDrafts?.find((d) => d.filename === file.name) ?? 
                      videoDrafts?.find((d) => d.filename === file.name)}
        <ImageUpload
          key={file.name}
          reason="PostAttachment"
          {file}
          working={Boolean(pending) || Boolean(pack)}
          removeClicked={pending ? undefined : 
            () => files = [...files.slice(0, f), ...files.slice(f + 1)]}
          attachmentUploadPack={pack}
          onUpload={depend}
          allowVideo={true}
        />
      {/each}
    </div>

    <div class={styles.Submit}>
      <Button on:click={post} disabled={!postable}>
        <span>{submitText}</span>
        <img src={chevvy} alt={submitText} aria-hidden={true} />
      </Button>
    </div>

    {#if error}
      <div class={styles.Error}>{error}</div>
    {/if}

    {#if showInset && echoPost}
      <DynamicPost post={echoPost} inset="echo" />
    {/if}
  </div>
</div>
