// libs/ui-bits/src/Button/Button.tsx
import classnames from 'classnames';
import {
  ButtonHTMLAttributes,
  CSSProperties,
  FormEventHandler,
  ReactNode,
} from 'react';

import styles from './Button.module.sass';

type Props = {
  disabled?: boolean;
  className?: string;
  children?: ReactNode;
  onClick?: FormEventHandler<HTMLButtonElement>;
  type?: ButtonHTMLAttributes<HTMLButtonElement>['type'];
  style?: CSSProperties;
};

/**
 * @noInheritDoc
 */
export const Button = (props: Props) => (
  <button
    disabled={props.disabled}
    className={classnames(styles.Button, props.className)}
    onClick={props.onClick}
    type={props.type ?? 'button'}
    style={props.style}
  >
    {props.children}
  </button>
);

// libs/si-bits/src/Button/Button.svelte
<script lang="ts">
  import styles from './Button.module.sass';
  
  let { 
    disabled = false,
    className = '',
    type = 'button' as 'button' | 'submit' | 'reset',
    style = {} as Record<string, string>
  } = $props();
</script>

<button
  {disabled}
  class={`${styles.Button} ${className}`}
  {type}
  {style}
  on:click
>
  {@render children?.()}
</button>
