// libs/si-bits/src/authForms/UserRegistrationForm.svelte
<script lang="ts">
  import { api, setCookie } from 'monolith-ts-api';
  import { Agreeable } from '../Agreeable';
  import { EmailInput } from '../EmailInput';
  import { PasswordInput } from '../PasswordInput';
  import { ShowTos } from '../ShowTos';
  import { shout } from '../Sonic';
  import { SubmitButton } from '../SubmitButton';
  import { UsernameInput } from '../UsernameInput';
  import { phrasebook } from '../phrasebook';

  let email = '';
  let username = '';
  let password = '';
  let emailValid = false;
  let usernameValid = false;
  let passwordValid = false;
  let agreed = false;
  let error: any = undefined;

  function handleSubmit() {
    shout('submitClicked', {});
    api.registerUser({
      email,
      username,
      password,
      agreed: agreed as true,
    })
    .then((sessionId) => {
      setCookie('sessionId', sessionId, 365);
      window.location.reload();
    })
    .catch((e) => error = e);
  }
</script>

<h2>{phrasebook.regFormTitle}</h2>

<EmailInput 
  oninput={(e) => email = e.detail}
  onvalidation={(e) => emailValid = e.detail}
/>

<UsernameInput
  oninput={(e) => username = e.detail}
  onvalidation={(e) => usernameValid = e.detail}
/>

<PasswordInput
  oninput={(e) => password = e.detail}
  onvalidation={(e) => passwordValid = e.detail}
/>

<Agreeable onchange={(e) => agreed = e.detail}>
  {phrasebook.termsLabel} <ShowTos>{phrasebook.termsLink}</ShowTos>
</Agreeable>

<SubmitButton
  disabled={!(emailValid && usernameValid && passwordValid && agreed)}
  onclick={handleSubmit}
>
  Register
</SubmitButton>

{#if error}
  <h3>{error}</h3>
{/if}

// libs/ui-bits/src/authForms/UserRegistrationForm.tsx
import { api } from 'monolith-ts-api';
import { useState } from 'react';

import { Agreeable } from '../Agreeable';
import { EmailInput } from '../EmailInput';
import { PasswordInput } from '../PasswordInput';
import { ShowTos } from '../ShowTos';
import { shout } from '../Sonic';
import { SubmitButton } from '../SubmitButton';
import { UsernameInput } from '../UsernameInput';
import { phrasebook } from '../phrasebook';
import { setCookie } from 'monolith-ts-api';

export const UserRegistrationForm = () => {
  const [email, setEmail] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [emailValid, setEmailValid] = useState(false);
  const [usernameValid, setUsernameValid] = useState(false);
  const [passwordValid, setPasswordValid] = useState(false);
  const [agreed, setAgreed] = useState(false);
  const [error, setError] = useState();
  return (
    <>
      <h2>{phrasebook.regFormTitle}</h2>
      <EmailInput onInput={setEmail} onValidation={setEmailValid} />
      <UsernameInput onInput={setUsername} onValidation={setUsernameValid} />
      <PasswordInput onInput={setPassword} onValidation={setPasswordValid} />
      <Agreeable onChange={setAgreed}>
        {phrasebook.termsLabel} <ShowTos>{phrasebook.termsLink}</ShowTos>
      </Agreeable>
      <SubmitButton
        disabled={!(emailValid && usernameValid && passwordValid && agreed)}
        onClick={() => {
          shout('submitClicked', {});
          api
            .registerUser({
              email,
              username,
              password,
              agreed: agreed as true,
            })
            .then((sessionId) => {
              setCookie('sessionId', sessionId, 365);
              window.location.reload();
            })
            .catch((e) => setError(e));
        }}
      >
        Register
      </SubmitButton>
      {error && <h3>{error}</h3>}
    </>
  );
};
