// libs/si-bits/src/AuthOverlay/AuthOverlay.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import classnames from 'classnames';
  import LoadingOverlay from '../LoadingOverlay/LoadingOverlay.svelte';
  import { listen } from '../Sonic';
  import type { ComponentType } from 'svelte';
  import hidden from '../hidden.module.sass';
  import styles from './AuthOverlay.module.sass';

  const $state = {
    form: null as ComponentType | null,
    loading: false
  };

  onMount(() => {
    listen('showAuth', (newForm) => $state.form = newForm);
    listen('submitClicked', () => $state.loading = true);
    listen('formReplied', () => $state.loading = false);
  });
</script>

<div 
  class={classnames(styles.AuthOverlay, {
    [hidden.hidden]: !$state.form
  })}
>
  <div class={styles.AuthForm}>
    <div 
      class={classnames(styles.interactives, {
        [hidden.hidden]: $state.loading
      })}
    >
      <button 
        class={styles.Close}
        on:click={() => $state.form = null}
      />
      {#if $state.form}
        <svelte:component this={$state.form} />
      {/if}
    </div>
    <LoadingOverlay shown={$state.loading} />
  </div>
</div>

// libs/ui-bits/src/AuthOverlay/AuthOverlay.tsx
import classnames from 'classnames';
import { ReactNode, useEffect, useState } from 'react';

import { LoadingOverlay } from '../LoadingOverlay';
import { listen } from '../Sonic';
import hidden from '../hidden.module.sass';
import styles from './AuthOverlay.module.sass';

export const AuthOverlay = () => {
	const [form, setForm] = useState<ReactNode>();
	const [loading, setLoading] = useState(false);
	useEffect(() => {
		listen('showAuth', setForm);
		listen('submitClicked', () => setLoading(true));
		listen('formReplied', () => setLoading(false));
	}, []);
	return (
		<div
			className={classnames(styles.AuthOverlay, {
				[hidden.hidden]: !form,
			})}
		>
			<div className={styles.AuthForm}>
				<div
					className={classnames(styles.interactives, {
						[hidden.hidden]: loading,
					})}
				>
					<button
						className={styles.Close}
						onClick={() => setForm(undefined)}
					></button>
					{form}
				</div>
				<LoadingOverlay shown={loading} />
			</div>
		</div>
	);
};
