// libs/si-bits/src/Nav/DesktopNav.svelte
<script lang="ts">
  import { LevelBadge } from '../LevelBadge';
  import { Backdrop } from '../Backdrop';
  import { Image } from '../Image';
  import { Link } from '../Link';
  import { CoolLink } from '../CoolLink';
  import { NavLogo } from '../NavLogo';
  import { shout } from '../Sonic';
  import { UserLoginForm, UserRegistrationForm } from '../authForms';
  import { phrasebook } from '../phrasebook';
  import styles from './DesktopNav.module.sass';
  import { Lingo } from '../Lingo';

  export let url: URL;
  export let sessionId: string;
  

  const showAuth = (form: any) => () => shout('showAuth', form);
  import { createEventDispatcher } from 'svelte';
	import type { string } from '../../../../../from-schema/dist/bson/primitives';
	import type { User } from '@lyku/json-models';
	// import { currentUser } from '../currentUserStore';
  const dispatch = createEventDispatcher();
  const join = () => dispatch('join');
  const login = () => dispatch('login');
// const user = $currentUser;
export let user: User;
  console.log('user', user);
</script>

<div class={styles.DesktopNav}>
  <div class={styles.DesktopNavContainer}>
    <div class={styles.InnerDesktopNav}>
      <Backdrop />
      <NavLogo />
      {#if $user}
        <CoolLink href="/tail" isActive={url.pathname.startsWith('/tail')}>{phrasebook.navTailored}</CoolLink>
      {/if}
      <CoolLink href="/hot" isActive={url.pathname.startsWith('/hot')}>{phrasebook.navHot}</CoolLink>
      <CoolLink href="/play" isActive={url.pathname.startsWith('/play')}>{phrasebook.navPlay}</CoolLink>
      
      <span class={styles.cluster}>
        {#if $user}
          <span class={styles.welcome}>
            {phrasebook.navWelcome}
            <Link href="/profile">
              <span>{user.username}!</span>
              <Image
                shape="circle"
                size="s"
                url={user.profilePicture}
              />
            </Link>
            <span class={styles.badgeHolder}>
              <LevelBadge points={user.points ?? 0n} progress={true} />
            </span>
          </span>
        {:else}
          <Link on:click={join}>
            {phrasebook.navRegister}
          </Link>
          <Link on:click={login}>
            {phrasebook.navLogin}
          </Link>
        {/if}
        <Lingo />
      </span>
    </div>
  </div>
  <div class={styles.DesktopNavSpacer}></div>
</div>

// libs/ui-bits/src/Nav/DesktopNav.tsx
import { ReactNode } from 'react';
import { LevelBadge } from '../LevelBadge';
import { Backdrop } from '../Backdrop';
import { Image } from '../Image';
import { Link } from '../Link';
import { CoolLink } from '../CoolLink';
import { NavLogo } from '../NavLogo';
import { shout } from '../Sonic';
import { UserLoginForm, UserRegistrationForm } from '../authForms';
import { phrasebook } from '../phrasebook';
import styles from './DesktopNav.module.sass';
import { Lingo } from '../Lingo';
import { useCurrentUser } from '../currentUserStore';
// import { getDocsPage } from '../linkToDocs';
import { sessionId } from 'monolith-ts-api';

const showAuth = (form: ReactNode) => () => shout('showAuth', form);

export const DesktopNav = () => {
	const user = useCurrentUser();
	return (
		<div className={styles.DesktopNav}>
			<div className={styles.DesktopNavContainer}>
				<div className={styles.InnerDesktopNav}>
					<Backdrop />
					<NavLogo />
					{user && sessionId && (
						<CoolLink href="/tail">{phrasebook.navTailored}</CoolLink>
					)}
					<CoolLink href="/hot">{phrasebook.navHot}</CoolLink>
					<CoolLink href="/play">{phrasebook.navPlay}</CoolLink>
					{/*<CoolLink href={getDocsPage()} target="_blank">*/}
					{/*	Code*/}
					{/*</CoolLink>*/}
					{/* <Link href="/roadmap">Roadmap</Link> */}
					<span className={styles.cluster}>
						{user && sessionId ? (
							<span className={styles.welcome}>
								{phrasebook.navWelcome}{' '}
								<Link href="/profile">
									<span>{user.username}!</span>{' '}
									<Image
										shape={'circle'}
										size={'s'}
										url={user.profilePicture}
									/>
								</Link>
								<span className={styles.badgeHolder}>
									<LevelBadge points={user.points ?? 0} progress={true} />
								</span>
							</span>
						) : (
							<>
								<Link onClick={showAuth(<UserRegistrationForm />)}>
									{phrasebook.navRegister}
								</Link>
								<Link onClick={showAuth(<UserLoginForm />)}>
									{phrasebook.navLogin}
								</Link>
							</>
						)}
						<Lingo />
					</span>
				</div>
			</div>
			<div className={styles.DesktopNavSpacer}></div>
		</div>
	);
};
