// libs/si-bits/src/pages/Hot.svelte
<script lang="ts">
  import { api } from 'monolith-ts-api';
  import { PostList } from '../PostList.svelte';
  import styles from './Feed.module.sass';

  let postsPromise = api.listHotPosts({});
</script>

<div class={styles.FeedPage}>
  {#await postsPromise}
    <p>Loading posts...</p>
  {:then response}
    <div class={styles.Feed}>
      <PostList posts={response?.posts ?? []} />
    </div>
  {:catch error}
    <h3>{String(error)}</h3>
  {/await}
</div>

// libs/ui-bits/src/pages/Hot.tsx
import { api } from 'monolith-ts-api';
import { PostList } from '../PostList';
import styles from './Feed.module.sass';
import { Await } from 'awaitx';

/**
 * @category page
 * Hot
 * @returns a FeedPage containing the hottest posts
 */
export const Hot = () => (
	<div className={styles.FeedPage}>
		<Await
			source={() => api.listHotPosts({})}
			then={posts => (
				<div className={styles.Feed}>
					<PostList posts={posts ?? []} />
				</div>
			)}
			fail={error => <h3>{String(error)}</h3>}
			meanwhile={<>Loading posts...</>}
		/>
	</div>
);
