// libs/si-bits/src/pages/Stream.svelte
<script lang="ts">
	import { ChatBox } from '../ChatBox';
	import { VideoList } from '../VideoList';
	import { Fof } from '../Fof';
	import { Tv } from '../Tv';
	import { TvBox } from '../TvBox';
	import { api } from '@lyku/monolith-ts-api';
	import type { Channel } from '@lyku/monolith-ts-api';

	let channelName = window.location.pathname.substring(1);
	let channelPromise = api.getChannel({ name: channelName });
</script>

{#await channelPromise}
	<p>Loading...</p>
{:then channel}
	<TvBox>
		<Tv {channel}>
			<Fof>{channel?.name ?? 'LYKU'}</Fof>
		</Tv>
	</TvBox>

	<ChatBox {channel} />
	<br />

	{#if channel}
		<VideoList {channel} />
	{/if}
{:catch error}
	<p>Error loading channel: {error.message}</p>
{/await}

// libs/ui-bits/src/pages/Stream.tsx
import { ChatBox } from '../ChatBox';
import { VideoList } from '../VideoList';
import { Fof } from '../Fof';
import { Tv } from '../Tv';
import { TvBox } from '../TvBox';
import { api } from 'monolith-ts-api';
import { Await } from 'awaitx';

export const Stream = () => {
	const channelName = window.location.pathname.substring(1);
	return (
		<Await
			source={() => api.getChannel({ name: channelName })}
			then={channel => (
				<>
					<TvBox>
						<Tv channel={channel}>
							<Fof>{channel?.name ?? 'LYKU'}</Fof>
						</Tv>
					</TvBox>
					<ChatBox channel={channel}></ChatBox>
					<br />
					{channel && <VideoList channel={channel} />}
				</>
			)}
		/>
	);
};
