// libs/si-bits/src/pages/ViewGroup.svelte
<script lang="ts">
    import { api, sessionId } from 'monolith-ts-api';
    import { PostList } from '../PostList.svelte';
    import { getContext } from 'svelte';
    import { Await } from 'awaitx';

    // Get groupId from URL path
    const groupId = window.location.pathname.split('/g/')?.[1];
    
    // Get cache from context
    const cache: any = getContext('cache');
    $: group = $cache?.groups?.[groupId];

    // Create posts promise
    const postsPromise = sessionId
        ? api.listFeedPosts({ groups: [BigInt(groupId)] })
        : api.listFeedPostsUnauthenticated({ groups: [BigInt(groupId)]});
</script>

{#if group}
    <h2>{group.name}</h2>
{/if}

{#await postsPromise}
    <p>Loading posts...</p>
{:then posts}
    <PostList {posts} />
{:catch error}
    <p>Error loading posts: {error.message}</p>
{/await}

// libs/ui-bits/src/pages/ViewGroup.tsx
import { api, sessionId } from 'monolith-ts-api';
import { PostList } from '../PostList';
import { useCacheSingleton } from '../CacheProvider';
import { Await } from 'awaitx';

export const ViewGroup = () => {
	const groupId = document.location.pathname.split('/g/')?.[1];
	const [group] = useCacheSingleton('groups', groupId);
	return (
		<Await
			source={() =>
				sessionId
					? api.listFeedPosts({ groups: [groupId] })
					: api.listFeedPostsUnauthenticated({ groups: [groupId] })
			}
			then={(posts) => (
				<>
					<h2>{group?.name}</h2>
					<PostList posts={posts} />
				</>
			)}
		/>
	);
};
