// libs/si-bits/src/Banner/Banner.svelte
<script lang="ts">
	import classnames from 'classnames';
	import bannerStyles from './Banner.module.sass';

	// No need to explicitly declare children - it's a built-in prop
	let { children } = $props();
</script>

<div class={classnames(bannerStyles.Banner)}>
  <h1>{@render children?.()}</h1>
</div>

// libs/ui-bits/src/Banner/Banner.tsx
import classnames from 'classnames';
import { FC, ReactNode } from 'react';

import bannerStyles from './Banner.module.sass';

type BannerProps = { children?: ReactNode };

/**
 * @noInheritDoc
 */
export const Banner: FC<BannerProps> = (props) => (
	<div className={classnames(bannerStyles.Banner)}>{props.children}</div>
);
