// libs/si-bits/src/ProfilePicture/ProfilePicture.svelte
<script lang="ts">
  import { Image } from './Image.svelte';
  import styles from './Image/Image.module.sass';
  import smile from './smile.png';
  
  export let url = smile;
  export let alt: string | undefined = undefined;
  export let size: number | undefined = undefined;
</script>

<span class={styles.ProfilePicture}>
  <Image shape="squircle" {url} {alt} {size} />
</span>

// libs/si-bits/src/ProfilePicture.tsx
import { Image, ImageProps } from './Image';
import styles from './Image/Image.module.sass';
import smile from './smile.png';
export type PPP = Omit<ImageProps, 'squircle'>;
export const ProfilePicture = (props: PPP) => (
	<span className={styles.ProfilePicture}>
		<Image shape={'squircle'} url={smile} {...props} />
	</span>
);
