// libs/ui-bits/src/Backdrop/Backdrop.tsx
import { formImageUrl } from '../formImageUrl';
import styles from './Backdrop.module.sass';
import drop from './drop.png';

export const Backdrop = ({ image }: { image?: string }) => (
  <div className={styles.Backdrop}>
    <img src={image ? formImageUrl(image) : drop} alt="Backdrop" />
  </div>
);

// libs/si-bits/src/Backdrop/Backdrop.svelte
<script lang="ts">
  import { formImageUrl } from '../formImageUrl';
  import styles from './Backdrop.module.sass';
  import drop from './drop.png';

  let { image } = $props<{
    image?: string;
  }>();
</script>

<div class={styles.Backdrop}>
  <img src={image ? formImageUrl(image) : drop} alt="Backdrop" />
</div>
